//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetRegister
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public decimal cost { get; set; }
        public int assetTypeId { get; set; }
        public Nullable<int> userId { get; set; }
        public System.DateTime purchaseDate { get; set; }
    
        public virtual AssetType AssetType { get; set; }
        public virtual User User { get; set; }
    }
}
